language: php

php:
  - 7.1
  - 7.2
  - 7.3


before_script:
  - composer install -n --dev --prefer-source
  - export XDEBUG_MODE=coverage

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
